module.exports = {
  awsSidebar: [
    {
      type: "autogenerated",
      dirName: "aws", // Path relative to the notes folder
    },
  ],
  githubSidebar: [
    {
      type: "autogenerated",
      dirName: "github", // Path relative to the notes folder
    },
  ],
  graphqlSidebar: [
    {
      type: "autogenerated",
      dirName: "graphql", // Path relative to the notes folder
    },
  ],
  typeormSidebar: [
    {
      type: "autogenerated",
      dirName: "typeorm", // Path relative to the notes folder
    },
  ],
  javascriptSidebar: [
    {
      type: "autogenerated",
      dirName: "javascript", // Path relative to the notes folder
    },
  ],

  dockerSidebar: [
    {
      type: "autogenerated",
      dirName: "docker", // Path relative to the notes folder
    },
  ],
  nodejsSidebar: [
    {
      type: "autogenerated",
      dirName: "nodejs", // Path relative to the notes folder
    },
  ],
  reactjsSidebar: [
    {
      type: "autogenerated",
      dirName: "reactjs", // Path relative to the notes folder
    },
  ],
  bunSidebar: [
    {
      type: "autogenerated",
      dirName: "bun", // Path relative to the notes folder
    },
  ],
};
